// react-project/src/system/login/index.tsx
import React from 'react';
import { useNavigate } from 'react-router-dom'

import { Form, Input, Button, Checkbox } from 'antd'
import './style.scss'

import { useAppDispatch, useAppSelector } from '@/hooks'
import { login } from '@/store/reducers/user'

export default () => {
  const navigate = useNavigate()
  const dispatch = useAppDispatch()

  const onFinish = (values:any) => {
    console.log('登录', values)
    dispatch(login(values)).then(res=>{
      console.log('登录成功', res)
      navigate('/good')
    })
  }

  return (
    <div className='qf-login'>
      <div className='wrap'>
        <Form
          name="basic"
          labelCol={{span:6}}
          wrapperCol={{span:16}}
          initialValues={{remember: true}}
          onFinish={onFinish}
          autoComplete="off"
        >
          <Form.Item
            label="用户名"
            name="username"
            rules={[
              {
                required: true,
                message: 'Please input your username!',
              },
            ]}
          >
            <Input />
          </Form.Item>

          <Form.Item
            label="密码"
            name="password"
            rules={[
              {
                required: true,
                message: 'Please input your password!',
              },
            ]}
          >
            <Input.Password />
          </Form.Item>

          <Form.Item
            name="remember"
            valuePropName="checked"
            wrapperCol={{offset:6,span:16}}
          >
            <Checkbox>记住我</Checkbox>
          </Form.Item>

          <Form.Item
            wrapperCol={{offset:6,span:16}}
          >
            <Button
              type="primary"
              htmlType="submit"
            >
              登录
            </Button>
          </Form.Item>
        </Form>
      </div>
    </div>
  )
}

// vue-webapp/src/views/user/Login.vue
<template>
<div class="qf-login">
  <QfNavBar>
    <template>登录</template>
    <template #action>
      <div>注册</div>
    </template>
  </QfNavBar>

  <van-form @submit="onSubmit">
    <van-field
      v-model="form.username"
      name="用户名"
      label="用户名"
      placeholder="用户名"
      :rules="[{ required: true, message: '请填写用户名' }]"
    />
    <van-field
      v-model="form.password"
      type="password"
      name="密码"
      label="密码"
      placeholder="密码"
      :rules="[{ required: true, message: '请填写密码' }]"
    />
    <div style="margin: 16px;">
      <van-button round block type="info" native-type="submit">登录</van-button>
    </div>
  </van-form>
</div>
</template>

<script>
import { QfNavBar } from '@/components'
import { mapActions } from 'vuex'
export default {
  components: { QfNavBar },
  data() {
    return {
      form: {
        username: '',
        password: ''
      }
    }
  },
  created() {
    console.log('login page created')
  },
  methods: {
    ...mapActions('user', ['login']),
    onSubmit() {
      // 数据校验
      this.login(this.form).then(()=>{
        this.$toast({
          type: 'success',
          message: '登录成功'
        })
        this.timer = setTimeout(()=>{
          this.$router.back()
        }, 2000)
      })
    }
  },
  beforeDestory() {
    clearTimeout(this.timer)
  }
}
</script>

<style lang="scss" scoped>
</style>
