// vue-element-admin/src/views/system/user-manage.vue
<template>
<div class="app-container">
  <div class="filter">
    <el-row>
      <el-col :span="24">
        <el-input
          style='width:120px;'
          v-model="filter.name"
          placeholder="商品名称"
          @clear='count++'
          @change='count++'
          clearable
        />

        <!-- 角色下拉 -->

        <el-button type="primary" icon="el-icon-search" @click='count++'>搜索</el-button>
        <el-button type="primary" icon="el-icon-edit" @click='addUser'>新增</el-button>
      </el-col>
    </el-row>
  </div>

  <div class="table" style="marginTop:20px;">
    <el-table
      :data="userArr"
      size='mini'
      border
      style="width: 100%">
      <el-table-column
        label="序号"
        type='index'
        width='80'
        align='center'>
      </el-table-column>
      <el-table-column
        prop="username"
        label="用户"
        align='center'/>
      <el-table-column
        prop="role"
        label="角色"
        align='center'>
      </el-table-column>
      <el-table-column
        prop="role_name"
        align='center'
        label="角色名称">
      </el-table-column>
      <el-table-column
        prop="status"
        align='center'
        label="状态">
        <template slot-scope='scope'>
          <div>{{scope.row.status?"正常":"禁用"}}</div>
        </template>
      </el-table-column>
      <el-table-column
        prop="handle"
        align='center'
        width='240'
        label="操作">
        <template slot-scope='scope'>
          <el-button
            size='mini'
            :disabled='scope.row.role==="admin"'
            @click='userHandle(scope.row)'
            :type='(scope.row.status?"danger":"primary")'>
            {{scope.row.status?"禁用":"启用"}}
          </el-button>
        </template>
      </el-table-column>
    </el-table>
  </div>

  <div class="page" style="marginTop:60px;">
    <el-pagination
      @size-change="sizeChange"
      @current-change="pageChange"
      :current-page="filter.page"
      :page-sizes="[2,5,10,20]"
      :page-size="filter.size"
      layout="total, sizes, prev, pager, next, jumper"
      background
      :total="total">
    </el-pagination>
  </div>

  <!-- 添加用户的弹框 -->
  <el-dialog title="添加用户" :visible.sync="show">
    <el-row>
      <el-col span='4'>用户名:</el-col>
      <el-col span='20'>
        <el-input v-model="userForm.username" />
      </el-col>
    </el-row>
    <el-row>
      <el-col span='4'>用户名:</el-col>
      <el-col span='20'>
        <el-select v-model="userForm.role" placeholder="请选择角色">
          <el-option
            v-for='item in roleArr'
            :key='item._id'
            :label="item.role_name"
            :value="item.role" />
        </el-select>
      </el-col>
    </el-row>
    <div slot="footer" class="dialog-footer">
      <el-button @click="show = false">取 消</el-button>
      <el-button type="primary" @click="submitUser">确 定</el-button>
    </div>
  </el-dialog>

</div>
</template>

<script>
export default {
  name: 'UserManage',
  data() {
    return {
      count: 0,
      filter: {
        name: '',
        page: 1,
        size: 2
      },
      userArr: [],
      total: 0,
      userForm: {
        username: '',
        role: ''
      },
      show: false,
      roleArr: []
    }
  },
  created() {
    this.init(this.filter)
    this.$api.fetchRoleList()
      .then(res=>this.roleArr = res.list)
  },
  activated () { this.init(this.filter) },
  watch: {
    count() {
      const filter = this.copy(this.filter)
      filter.page = 1
      this.filter = filter
      this.init(filter)
    }
  },
  methods: {
    init(params) {
      this.$api.fetchUserList(params)
        .then(res=>{
          console.log('用户列表', res)
          this.userArr = res.list
          this.total = res.total
        })
    },
    copy(target) {
      return JSON.parse(JSON.stringify(target))
    },
    sizeChange (val) {
      const filter = this.copy(this.filter)
      filter.page = 1
      filter.size = val
      this.filter = filter
      this.init(filter)
    },
    pageChange(val) {
      const filter = this.copy(this.filter)
      filter.page = val
      this.filter = filter
      this.init(filter)
    },
    // 打开添加用户的弹框
    addUser() {
      this.userForm = { username: '', role: '' }
      this.show = true
    },
    // 添加用户
    submitUser() {
      console.log('提交', this.userForm)
      const params = {
        ...this.userForm,
        role_name: this.roleArr.find(ele=>ele.role===this.userForm.role).role_name
      }
      // 表单验证，表单验证成功
      this.$api.fetchUserAdd(params)
        .then(()=>{
          this.init(this.filter)
          this.show = false
        })
    },
    // 启用或启用
    userHandle(row) {
      const params = {
        id: row._id,
        status: (row.status+1)%2
      }
      this.$api.fetchUserUpd(params)
        .then(()=>this.init(this.filter))
    }
  }
}
</script>

<style lang="scss" scoped>
.app-container {
  min-width: 980px;
}
</style>

// react-admin/src/views/user/UserManage.js
import { useDispatch, useSelector } from 'react-redux'
import { useState, useEffect, useMemo } from 'react'

import { Row, Col, Input, Select, Button, Table, Tag, Space, message } from 'antd'
import './style.scss'

import RoleSelect from './components/RoleSelect'
import { addUser, resetAdmin, listUser, statusUser } from '@/store/actions'

// 新增用户的表单绑定
const initForm = {
  username:'',
  role:'',
  role_name:'',
  id_card:'',
  mobile:'',
  done: 0
}
export default () => {
  const dispatch = useDispatch()
  // 用于新增用户的表单绑定
  const [form, setForm] = useState(initForm)
  // 用于列表查询
  const [params, setParams] = useState({page:1,size:2,username:''})

  const { done, userTable } = useSelector(state=>state.admin)

  // 当用户新增成功时执行
  useEffect(()=>{
    if(done===1) {
      message.success('添加成功')
      setForm(initForm)
      // dispatch(listUser(params))
      setParams({...params,page:1})
    }
  }, [done])

  // 当row操作（禁用或启用）时执行
  useEffect(()=>{
    if (done===2) dispatch(listUser(params))
  }, [done])

  // 当页面初始化、params变化时执行
  useEffect(()=>{
    dispatch(listUser(params))
  }, [params])

  // 事件：点击“禁用”或“启用”时
  const rowHandle = row => {
    console.log('row', row)
    dispatch(statusUser({user_id:row._id, status:(row.status+1)%2}))
  }

  // 用于“用户新增”的表单取值
  const formChange = (key, ev) => {
    // 对RoleSelect有问题
    if (key==='role') {
      setForm({...form, role:ev.role, role_name:ev.role_name})
    } else {
      setForm({...form, [key]:ev.target.value})
    }
  }

  // 事件：点击“添加”用户时执行
  const submitAdd = () => {
    console.log('提交', form)
    // 表单校验
    dispatch(addUser(form))
  }

  const columns = useMemo(()=>(
    [
      {
        align: 'center',
        title: '序号',
        key: 'index',
        dataIndex: 'id',
        render: (text,row,index)=><div>{index}</div>
      },
      {
        align: 'center',
        title: '用户名',
        dataIndex: 'username',
        key: 'username',
        render: text => <a>{text}</a>,
      },
      {
        align: 'center',
        title: '角色',
        dataIndex: 'role',
        key: 'role',
      },
      {
        align: 'center',
        title: '角色名称',
        dataIndex: 'role_name',
        key: 'role_name',
      },
      {
        align: 'center',
        title: '状态',
        dataIndex: 'status',
        key: 'status',
        render: status=>(status?'正常':'已被禁用')
      },
      {
        align: 'center',
        title: '操作',
        key: 'tags',
        dataIndex: 'tags',
        render: (text,row) => (
          <>
            <Button
              size='small'
              onClick={()=>rowHandle(row)}
              type="primary">
              { row.status ? '禁用' : '启用' }
            </Button>
            <Button size='small' type="primary" style={{marginLeft:'10px'}}>编辑</Button>
            <Button size='small' danger style={{marginLeft:'10px'}}>删除</Button>
          </>
        ),
      }
    ]
  ), [])

  return (
    <div className='qf-user-manage'>

      <div className='user-add'>
        <Row align='middle'>
          <Col span={2} className='label'>用户名:</Col>
          <Col span={4}>
            <Input value={form.username} onChange={ev=>formChange('username',ev)} />
          </Col>
          <Col span={2} className='label'>角色:</Col>
          <Col span={4}>
            <RoleSelect value={form.role} onChange={ev=>formChange('role',ev)} />
          </Col>
          <Col span={2} className='label'>身份证:</Col>
          <Col span={6}>
            <Input value={form.id_card} onChange={ev=>formChange('id_card',ev)} />
          </Col>
        </Row>
        <Row align='middle' style={{marginTop:'20px'}}>
          <Col span={2} className='label'>手机号:</Col>
          <Col span={4}>
            <Input value={form.mobile} onChange={ev=>formChange('mobile',ev)} />
          </Col>
        </Row>
        <Row align='middle' style={{marginTop:'20px'}}>
          <Col span={2} className='label'></Col>
          <Col span={4}>
            <Button type="primary" onClick={submitAdd}>添加</Button>
          </Col>
        </Row>
      </div>

      <div className='user-table'>
        <Table
          columns={columns}
          dataSource={userTable.list||[]}
          rowKey='_id'
          pagination={{
            total: userTable.total||0,
            current: params.page,
            defaultPageSize: params.size,
            showTotal: (total, range) => `第${range[0]}-${range[1]}条 / 总共${total}条`,
            pageSizeOptions: [2,5,10,20],
            size: 'small',
            showQuickJumper: true,
            showSizeChanger: true,
            onChange:(page,size) => setParams({...params,page,size})
          }}
          title={() => (
            <Input.Search
              style={{width:'150px'}}
              placeholder="搜索"
              allowClear
              onSearch={val=>setParams({...params,username:val,page:1})}
            />
          )}
        />
      </div>
    </div>
  )
}
